version: "3"
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: database123
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
    volumes:
      - ${HOME}/database/spike-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
