version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  server:
    image: node-express
    ports:
      - 8000:8000
