version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: db123
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
  server:
    image: node-express
    ports:
      - 13000:3000
