# ADMIN
### Create all tables
GET http://localhost:8000/setup-tables

# ASSIGNMENTS   
### Get all assignments
GET http://localhost:8000/assignments

### Add new assignment Example A
POST http://localhost:8000/assignments
Content-Type: application/json

{
    "assignment_name": "Product Owner",
    "company_name": "GigAssembly",
    "company_image_url": ""
}

### Add new assignment Example B
POST http://localhost:8000/assignments
Content-Type: application/json

{
    "assignment_name": "Senior Frontend Developer II",
    "company_name": "Zalando",
    "company_image_url": ""
}
 
# CANDIDATES
### Get all candidates from assignment id
GET http://localhost:8000/candidates/1
 
### Add new candidate Example A (assigment 1)
POST http://localhost:8000/candidates
Content-Type: application/json

{
    "assignment_id": 1,
    "linked_in_url": "https://www.linkedin.com/in/arianjavdan/",
    "candidate_name": "Alexia Alvarez",
    "candidate_job_title": "Architect",
    "candidate_image_url": "https://media.licdn.com/dms/image/D4D03AQGmLhBIEPbddw/profile-displayphoto-shrink_800_800/0/1696516150220?e=1715817600&v=beta&t=b_UQJhoulWjmu1nxqfSTxjy_Xa0C2jQnqWp7QplbAX8",
    "company_name": "Municipio de Guayaquil",
    "company_duration_in_months": 36,
    "company_image_url": "https://media.licdn.com/dms/image/C560BAQGKTrPVBNotbA/company-logo_100_100/0/1631305957530?e=1718236800&v=beta&t=wKZMj4vchmY7je4Rtk_HUXOuVytjLxE0_AFna6Q14zY",
    "notes": "Just transitioned to data engineering, before that was a sofware developer (which makes sense) but is too junior",
    "relevance": 0,
    "contact_status": 0,
    "contact_date": null
}

### Add new candidate Example B (assigment 1)
POST http://localhost:8000/candidates
Content-Type: application/json

{
    "assignment_id": 1,
    "linked_in_url": "https://www.linkedin.com/in/love-eklund-39a9a0174/",
    "candidate_name": "Love Eklund",
    "candidate_job_title": "Data Engineer",
    "candidate_image_url": "https://media.licdn.com/dms/image/C5603AQHYFIB1ahxDew/profile-displayphoto-shrink_400_400/0/1542622589556?e=1715817600&v=beta&t=1h-ylFdRlAW82NDq23ZTFPGk82OiANbHrPhhNSLla38",
    "company_name": "TriOptima",
    "company_duration_in_months": 11,
    "company_image_url": "https://media.licdn.com/dms/image/C4E0BAQEHPsW_up7JZQ/company-logo_100_100/0/1649681136982/trioptima_logo?e=1718236800&v=beta&t=juKOVbr5CkqxYqqlFo5snqb6nSHSrjpHUHJsZQ4zs4I",
    "notes": "Switched to data engineering, before that was a data scientist/analyist",
    "relevance": 0,
    "contact_status": 0,
    "contact_date": null
}

### Add new candidate Example C (assigment 2)
POST http://localhost:8000/candidates
Content-Type: application/json

{
    "assignment_id": 2,
    "linked_in_url": "https://www.linkedin.com/in/eduardo-alvarez-nowak/",
    "candidate_name": "Eduardo Alvarez",
    "candidate_job_title": "Senior Frontend Developer",
    "candidate_image_url": "https://media.licdn.com/dms/image/C4E03AQHwKgpnjrXkZA/profile-displayphoto-shrink_400_400/0/1643017689481?e=1716422400&v=beta&t=yMUio3ZjuE8ceaHP-d62d7rbrBjiPahZGB0PsdRDV64",
    "company_name": "GitBook",
    "company_duration_in_months": 1,
    "company_image_url": "https://media.licdn.com/dms/image/D4E0BAQGDaMzI2n4ilw/company-logo_200_200/0/1702376699108/zalando_logo?e=1719446400&v=beta&t=md_qqWGYWX58GVAsGBF63FGOWPm0mKT2eNsiCuE0aPw",
    "notes": "Great profile but entered his new job less than a month ago!",
    "relevance": 0,
    "contact_status": 0,
    "contact_date": null
}