### Check you can connec to server
GET http://localhost:8000/

### Get all assigments
GET http://localhost:8000/assigments

### Intialize database
GET http://localhost:8000/setup

### Send a new assigment
POST http://localhost:8000/
Content-Type: application/json

{
    "assigment_name": "Data Engineer",
    "company_name": "Folksam"
}

