### Check you can connec to server
GET http://localhost:13000/

### Intialize database
GET http://localhost:13000/setup

### Get all assigments
GET http://localhost:13000/assigments


### Send a new assigment
POST http://localhost:13000/
Content-Type: application/json

{
    "assigment_name": "Data Engineer",
    "company_name": "Folksam"
}

